### ISSUE TITLE
Return error response

### ISSUE THREAD

**Issue by vespakoen** [sparksp/laravel-service#2]
Hi Phill,

I guess it would be a nice addition if the Service bundle could handle error codes,
Now I have to return something like Response::make(json_encode('error' => 'Something went wrong'), somecode).

What do you think?

x

**Comment by sparksp** [comment]
Sounds good; how would you (in an ideal PHP world) like to be able to configure/use those?

**Comment by vespakoen** [comment]
For future reference,

$service->status(somecode); // (somecode being the response code)

Worked perfectly!
